spring:
  datasource:
    url: jdbc:postgresql://${PG_HOST}:5432/${DATABASE_NAME}
  jpa:
    open-in-view: false
  profiles:
    active: prod

management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health, prometheus

melosys:
  kafka:
    aiven:
      brokers: ${KAFKA_BROKERS}
      keystorePath: ${KAFKA_KEYSTORE_PATH:/dev/zero}
      truststorePath: ${KAFKA_TRUSTSTORE_PATH:/dev/zero}
      credstorePassword: ${KAFKA_CREDSTORE_PASSWORD:pwd}
    producer:
      topic-name-aiven: ${KAFKA_SOKNAD_MOTTATT_TOPIC}
  systemuser:
    username: ${SRV_USERNAME}
    password: ${SRV_PASSWORD}

altinn:
  behandle-melding:
    url: ${ALTINN_BEHANDLE_MELDING_URL}
  informasjon:
    url: ${ALTINN_INFORMASJON_URL}
  download-queue:
    code: ${ALTINN_DQ_CODE}
    edition-code: ${ALTINN_DQ_EDITION_CODE}
  correspondence:
    code: ${ALTINN_CORRESPONDENCE_CODE}
    edition-code: ${ALTINN_CORRESPONDENCE_EDITION_CODE}
  username: ${ALTINN_USERNAME}
  password: ${ALTINN_PASSWORD}

dokgen:
  url: ${DOKGEN_URL}

sts:
  url: ${STS_URL}
  username: ${SRV_USERNAME}
  password: ${SRV_PASSWORD}

#Token-validering
no.nav.security.jwt.issuer:
  reststs:
    discovery-url: ${RESTSTS_URL}/.well-known/openid-configuration
    accepted-audience: srvmelosys
