apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: melosys-soknad-mottak
  namespace: teammelosys
  labels:
    team: teammelosys
spec:
  image: {{image}}
  port: 8080
  replicas:
    min: 1
    max: 1
  liveness:
    path: /actuator/health
    initialDelay: 100
    timeout: 10
  readiness:
    path: /actuator/health
    initialDelay: 100
    timeout: 10
  prometheus:
    enabled: true
    path: /actuator/prometheus
  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 512Mi
  azure:
    application:
      enabled: true
      tenant: {{TENANT_URL}}
  accessPolicy:
    inbound:
      rules:
        {{#each accessPolicy.inbound.rules }}
           - application: {{application}}
          {{/each }}
  ingresses:
    - {{ingress}}
  vault:
    enabled: true
  kafka:
    pool: {{ KAFKA_POOL }}


