apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: melosys-soknad-mottak
  namespace: {{namespace}}
  labels:
    team: teammelosys
spec:
  image: {{image}}
  port: 8080
  replicas:
    min: 1
    max: 1
  liveness:
    path: /actuator/health
    initialDelay: 20
    timeout: 10
  readiness:
    path: /actuator/health
    initialDelay: 20
    timeout: 10
  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 512Mi
  prometheus:
    enabled: false
    path: /actuator/prometheus
  vault:
    enabled: true



