spring:
  datasource:
    url: jdbc:postgresql://${PG_HOST}:5432/${DATABASE_NAME}
  jpa:
    open-in-view: false
  profiles:
    active: prod
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        enable.idempotence: true
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    properties:
      security.protocol: SASL_SSL
      sasl.mechanism: PLAIN
      sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="${melosys.systemuser.username}" password="${melosys.systemuser.password}";
      reconnect.backoff.ms: 1000

management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health

melosys:
  kafka:
    producer:
      topic-name: ${KAFKA_TOPIC}
  systemuser:
    username: ${SRV_USERNAME}
    password: ${SRV_PASSWORD}

altinn:
  informasjon:
    url: ${ALTINN_INFORMASJON_URL}
  service:
    code: ${ALTINN_SERVICE_CODE}
  username: ${ALTINN_USERNAME}
  password: ${ALTINN_PASSWORD}

mottak:
  fjern-fra-dq: ${FJERN_FRA_DQ}

sts:
  url: ${STS_URL}
  username: ${SRV_USERNAME}
  password: ${SRV_PASSWORD}

#Token-validering
no.nav.security.jwt.issuer:
  reststs:
    discovery-url: ${RESTSTS_URL}/.well-known/openid-configuration
    accepted-audience: srvmelosys
